### PR TITLE
Issue #210 submissions api

### LINKED ISSUE #210: API for getting exercises and submitting solutions
This would allow integration of non-browser clients with Mumuki.

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #210 

This PR adds two routes:

```
GET /api/exercises/:id
```

Which retrieves an exercise's JSON with at least the following fields:

```json
{"id":88,
"title":"celsiusToFahr",
"description":"....",
"created_at":"2015-04-24T05:42:20.463Z",
"updated_at":"2015-04-25T13:16:33.675Z",
"language_id":1,
"submissions_count":75,
"author_id":2,
"guide_id":47,
"locale":"es",
"hint":null,
"position":6,
"corollary":null,
"layout":"editor_right"}
```

and

```
POST /api/exercises/:id/submission
```

which expects a JSON like the following: 

```json
{"submitter_id":1, "exercise_id": 1, "content":"foo"}
```

and retrieves a Submission JSON with at least the following:

```json
{"status":"passed", "result": "....test runner output....", "expectation_results": [], "feedback": "..."}
```

For more details about `expectation_results`, see http://mumuki.org/mumuki/tech/plataforma/runners/lenguaje/2015/06/22/extendiendo-mumuki-runners.html

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@nscarcella

**Comment by nscarcella** [comment]
Sorry, missed the first notification :S Could you reopen?

**Comment by flbulgarelli** [comment]
@nscarcella done

**Comment by faloi** [comment]
@flbulgarelli @nscarcella can we resolve the conflicts and merge this?

**Comment by nscarcella** [comment]
Looks good to me

**Comment by faloi** [comment]
What should we do with this one?

**Comment by flbulgarelli** [comment]
Closing. We are finally not going to do such integration - tools that want to track students progress should directly communicate with teacher tools

**Pull request closed without merging**
