### PR TITLE
Offline support

### PR DESCRIPTION
**Pull request by rodri042**
The change in `request.rb` is deletable, it was my first attempt to run locally after the last pull :P
Anyway, I'm not sure about modifying the `/etc/host` of each student's notebook to load Mumuki.

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@faloi can you have a look at this?

**Comment by faloi** [comment]
I know you can do better than those `if`s. :stuck_out_tongue: 

At least, encapsulate the `Rails.configuration.offline_mode` somewhere. If you're in a good day you could also make that "somewhere" an strategy and delegate everything there, so we have all the mode-dependant config in the same place.

Oh, and be careful: Travis reports a broken build.

**Comment by rodri042** [comment]
Now better? :stuck_out_tongue: 

The broken build... ehm... yes... the error seems not to be related with the build (`The command "openssl aes-256-cbc -K $encrypted_81250995bc45_key -iv $encrypted_81250995bc45_iv -in escualo_rsa.enc -out escualo_rsa -d" failed and exited with 1 during .`).  Can it be something with the origin of the branch? (a fork in my account instead of being a branch of this repository).

**Comment by rodri042** [comment]
I'll create another PR with a branch inside the repo to see if Travis pass

**Pull request closed without merging**
