### PR TITLE
Feature clean design

### PR DESCRIPTION
**Pull request by flbulgarelli**
This PR wants to simplify and optimize the main flow: do guides in a chapter one by one . Other flows are not taken into account. 

* Removing original landing page - it was merged with the chapter page
* Removing exercise and guide search pages.
* Removed distracting visual elements like popovers
* Removed "Go to last guide" functionality, since now home is meaningful. 
* Removing guides tags
* Removing guide navigation and exercise navigation
* Using more body space
* Removing spinner
* Added breadcrumbs for guides and exercises
* Added guides and exercises listings
* Removed unused views
* Removed some unused css
* Consistent usage of btn-success

Colors improvements, branding, rewording, hamburgers are NOT included in this PR. It just addresses navigation problems.

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Home Page: 

screencapture-central-localmumuki-io-3000-1452609384691

**Comment by flbulgarelli** [comment]
screencapture-central-localmumuki-io-3000-guides-7-fundamentos-primeros-programas-1452611143069

**Comment by flbulgarelli** [comment]
screencapture-central-localmumuki-io-3000-exercises-65-fundamentos-primeros-programas-movimientos-1452611319778

**Comment by flbulgarelli** [comment]
@faloi

**Comment by faloi** [comment]
The search bar is quite big, isn't it? 

Other suggestions:
* I still don't like the chapters (home) page, but I don't have any proposals to improve it.
* The logout could be inside a drop down that appears after clicking on the user name.
* The name of the exercise could be moved to the navbar, replacing the search panel. In fact, the whole navigation thing could be moved there (the search could be replaced with just a glass button that expands the textbox when clicked).

**Comment by flbulgarelli** [comment]
@faloi  forget about last screenshots. 

Home: 

screencapture-central-localmumuki-io-3000-1452979770385

If you click on a chapter:

step2

If you click on an exercise or on start button

step3

If you select the chapter:

step4

If you select an a new guide

step5

**Comment by flbulgarelli** [comment]
PS: I tried moving the navigation to the navbar and it dind't look well. Perhaps we could try a glass button as @faloi suggests. Nevertheless, those are bigger changes that should be addressed in another issue. 

@aguspina @fedescarpa please review.

**Comment by aguspina** [comment]
@flbulgarelli The exercise view still having the margin on both sides?

**Comment by aguspina** [comment]
LGTM, please @flbulgarelli answer my question so I can merge this

**Comment by flbulgarelli** [comment]
@aguspina Yes

**Comment by aguspina** [comment]
@flbulgarelli Why?

**Comment by flbulgarelli** [comment]
@aguspina  It didn't look well with current layout yet. But with another exercise layout it could work!

**Pull request merged**
